# Generated by Django 6.0.4 on 2026-04-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('src', models.CharField(max_length=32)),
                ('dst', models.CharField(max_length=32)),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=16)),
                ('tag', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
