# Generated by Django 6.0.4 on 2026-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='callrecord',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='played_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='recording',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='duration',
            field=models.CharField(default='0 sec', max_length=20),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='status',
            field=models.CharField(choices=[('Answered', 'Answered'), ('No Answer', 'No Answer'), ('Busy', 'Busy'), ('Failed', 'Failed')], default='No Answer', max_length=16),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='tag',
            field=models.CharField(blank=True, choices=[('Important', 'Important'), ('Evidence', 'Evidence'), ('Suspect', 'Suspect'), ('Follow-up', 'Follow-up')], max_length=32, null=True),
        ),
    ]
